2025-08-19 17:33:06,420 INFO    MainThread:15006 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-19 17:33:06,421 INFO    MainThread:15006 [wandb_setup.py:_flush():80] Configure stats pid to 15006
2025-08-19 17:33:06,421 INFO    MainThread:15006 [wandb_setup.py:_flush():80] Loading settings from /Users/advaitdesai/.config/wandb/settings
2025-08-19 17:33:06,421 INFO    MainThread:15006 [wandb_setup.py:_flush():80] Loading settings from /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/wandb/settings
2025-08-19 17:33:06,421 INFO    MainThread:15006 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-19 17:33:06,421 INFO    MainThread:15006 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/wandb/run-20250819_173306-o5k7bccl/logs/debug.log
2025-08-19 17:33:06,422 INFO    MainThread:15006 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/wandb/run-20250819_173306-o5k7bccl/logs/debug-internal.log
2025-08-19 17:33:06,422 INFO    MainThread:15006 [wandb_init.py:init():830] calling init triggers
2025-08-19 17:33:06,422 INFO    MainThread:15006 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'env_id': 'Ant-v5', 'num_envs': 16, 'steps_per_env': 1024, 'gamma': 0.99, 'gae_lambda': 0.95, 'clip_eps': 0.2, 'learning_rate': 0.0003, 'epochs': 10, 'minibatch_size': 512, 'device': 'cpu', '_wandb': {}}
2025-08-19 17:33:06,422 INFO    MainThread:15006 [wandb_init.py:init():871] starting backend
2025-08-19 17:33:06,437 INFO    MainThread:15006 [wandb_init.py:init():874] sending inform_init request
2025-08-19 17:33:06,491 INFO    MainThread:15006 [wandb_init.py:init():882] backend started and connected
2025-08-19 17:33:06,495 INFO    MainThread:15006 [wandb_init.py:init():953] updated telemetry
2025-08-19 17:33:06,533 INFO    MainThread:15006 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-19 17:33:08,173 INFO    MainThread:15006 [wandb_init.py:init():1029] starting run threads in backend
2025-08-19 17:33:08,246 INFO    MainThread:15006 [wandb_run.py:_console_start():2494] atexit reg
2025-08-19 17:33:08,246 INFO    MainThread:15006 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-19 17:33:08,246 INFO    MainThread:15006 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-19 17:33:08,246 INFO    MainThread:15006 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-19 17:33:08,247 INFO    MainThread:15006 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-19 17:33:08,619 WARNING MsgRouterThr:15006 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 227, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-08-19 17:33:08,619 INFO    MsgRouterThr:15006 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
2025-08-19 17:33:09,883 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,887 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,887 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,887 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,888 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,889 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,890 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,891 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,891 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,892 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,892 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,892 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,892 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,893 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,894 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,895 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,895 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,895 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,895 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,898 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,901 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,907 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,908 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,908 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,909 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,910 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,912 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,913 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,913 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,914 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,914 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,914 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,915 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,916 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,916 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,917 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,918 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,918 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,918 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,918 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,919 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,919 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,919 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,919 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,919 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,919 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-19 17:33:09,919 ERROR   MainThread:15006 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
