2025-08-20 17:48:46,366 INFO    MainThread:49320 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-20 17:48:46,366 INFO    MainThread:49320 [wandb_setup.py:_flush():80] Configure stats pid to 49320
2025-08-20 17:48:46,366 INFO    MainThread:49320 [wandb_setup.py:_flush():80] Loading settings from /Users/advaitdesai/.config/wandb/settings
2025-08-20 17:48:46,366 INFO    MainThread:49320 [wandb_setup.py:_flush():80] Loading settings from /Users/advaitdesai/Programming/eklavya/arhan_execute/wandb/settings
2025-08-20 17:48:46,367 INFO    MainThread:49320 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-20 17:48:46,367 INFO    MainThread:49320 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/advaitdesai/Programming/eklavya/arhan_execute/wandb/run-20250820_174846-hhoichdu/logs/debug.log
2025-08-20 17:48:46,367 INFO    MainThread:49320 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/advaitdesai/Programming/eklavya/arhan_execute/wandb/run-20250820_174846-hhoichdu/logs/debug-internal.log
2025-08-20 17:48:46,367 INFO    MainThread:49320 [wandb_init.py:init():830] calling init triggers
2025-08-20 17:48:46,367 INFO    MainThread:49320 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'env_id': 'Ant-v5', 'num_envs': 128, 'steps_per_env': 1024, 'gamma': 0.99, 'gae_lambda': 0.95, 'clip_eps': 0.2, 'learning_rate': 0.0003, 'epochs': 30, 'minibatch_size': 65536, 'device': 'cpu', '_wandb': {}}
2025-08-20 17:48:46,367 INFO    MainThread:49320 [wandb_init.py:init():871] starting backend
2025-08-20 17:48:46,796 INFO    MainThread:49320 [wandb_init.py:init():874] sending inform_init request
2025-08-20 17:48:46,839 INFO    MainThread:49320 [wandb_init.py:init():882] backend started and connected
2025-08-20 17:48:46,841 INFO    MainThread:49320 [wandb_init.py:init():953] updated telemetry
2025-08-20 17:48:46,854 INFO    MainThread:49320 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-20 17:48:47,774 INFO    MainThread:49320 [wandb_init.py:init():1029] starting run threads in backend
2025-08-20 17:48:47,880 INFO    MainThread:49320 [wandb_run.py:_console_start():2494] atexit reg
2025-08-20 17:48:47,900 INFO    MainThread:49320 [wandb_run.py:_redirect():2342] redirect: wrap_raw
2025-08-20 17:48:47,900 INFO    MainThread:49320 [wandb_run.py:_redirect():2411] Wrapping output streams.
2025-08-20 17:48:47,900 INFO    MainThread:49320 [wandb_run.py:_redirect():2434] Redirects installed.
2025-08-20 17:48:47,902 INFO    MainThread:49320 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-20 17:48:50,436 INFO    MsgRouterThr:49320 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-08-20 17:48:51,735 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,750 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,750 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,750 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,752 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,752 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,753 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,753 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,753 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,754 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,755 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,755 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,755 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,755 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,756 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,756 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,756 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,756 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,758 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,758 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,758 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,758 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,759 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,759 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,759 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,759 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,761 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,762 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,762 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,762 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,763 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,763 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-08-20 17:48:51,763 ERROR   MainThread:49320 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2421, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 399, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 457, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1583, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 166, in send_record_publish
    self.send_server_request(server_req)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 146, in send_server_request
    self._send_message(msg)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 143, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/Users/advaitdesai/Programming/eklavya/test_venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 122, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
