2025-08-19 17:33:06,457 INFO    MainThread:15005 [wandb_setup.py:_flush():80] Current SDK version is 0.21.1
2025-08-19 17:33:06,457 INFO    MainThread:15005 [wandb_setup.py:_flush():80] Configure stats pid to 15005
2025-08-19 17:33:06,457 INFO    MainThread:15005 [wandb_setup.py:_flush():80] Loading settings from /Users/advaitdesai/.config/wandb/settings
2025-08-19 17:33:06,457 INFO    MainThread:15005 [wandb_setup.py:_flush():80] Loading settings from /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/wandb/settings
2025-08-19 17:33:06,457 INFO    MainThread:15005 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-19 17:33:06,457 INFO    MainThread:15005 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/wandb/run-20250819_173306-os8v69vi/logs/debug.log
2025-08-19 17:33:06,457 INFO    MainThread:15005 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /Users/advaitdesai/Programming/eklavya/week7/go2_walk_pth/wandb/run-20250819_173306-os8v69vi/logs/debug-internal.log
2025-08-19 17:33:06,458 INFO    MainThread:15005 [wandb_init.py:init():830] calling init triggers
2025-08-19 17:33:06,458 INFO    MainThread:15005 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'env_id': 'Ant-v5', 'num_envs': 16, 'steps_per_env': 1024, 'gamma': 0.99, 'gae_lambda': 0.95, 'clip_eps': 0.2, 'learning_rate': 0.0003, 'epochs': 10, 'minibatch_size': 512, 'device': 'cpu', '_wandb': {}}
2025-08-19 17:33:06,458 INFO    MainThread:15005 [wandb_init.py:init():871] starting backend
2025-08-19 17:33:06,473 INFO    MainThread:15005 [wandb_init.py:init():874] sending inform_init request
2025-08-19 17:33:06,520 INFO    MainThread:15005 [wandb_init.py:init():882] backend started and connected
2025-08-19 17:33:06,526 INFO    MainThread:15005 [wandb_init.py:init():953] updated telemetry
2025-08-19 17:33:06,564 INFO    MainThread:15005 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-19 17:33:08,617 WARNING MsgRouterThr:15005 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 227, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/Users/advaitdesai/Programming/eklavya/venv/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-08-19 17:33:08,620 INFO    MsgRouterThr:15005 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
